### ISSUE TITLE
Template doesn't work with zabbix agent 2

### ISSUE THREAD

**Issue by romphilippi** [Futur-Tech/futur-tech-zabbix-windows-update#1]
Hi,

I have a question, does this template work with zabbix agent2 ?
I tried to make it work, but without success.

Thank you for your feedback.

**Comment by GuillaumeHullin** [comment]
Did you manage to get it to work?
I'm using Zabbix Agent 2 and it works for me.

**Comment by romphilippi** [comment]
Yes, by rechecking all the configuration I finally found what was wrong.
